# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: edabackenddaii
service: eventify-eda-be

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  profile: aws-academy
  role: arn:aws:iam::747661705570:role/LabRole
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource: "arn:aws:execute-api:us-east-1:*:*/*/*/@connections/*"

package:
  patterns:
    - '!**'
    - api/app.py
    - api/websocket.py
    - handler.py

functions:
  testHandler:
    handler: handler.lambda_handler
    package:
      individually: true
    events:
      - eventBridge:
          eventBus: default
          pattern:
            source:
              - my.application
            detail-type:
              - test

  websocketConnect:
    handler: api.websocket.connect
    events:
      - websocket:
          route: $connect

  websocketDisconnect:
    handler: api.websocket.disconnect
    events:
      - websocket:
          route: $disconnect

  websocketDefault:
    handler: api.websocket.default
    events:
      - websocket:
          route: $default

  restApi:
    handler: api.app.handler
    package:
      individually: true
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    useDownloadCache: true
    useStaticCache: true
