# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: edabackenddaii
service: eventify-eda-be

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: dev
  role: arn:aws:iam::442042507897:role/LabRole
  vpc:
    securityGroupIds:
      - Ref: PublicSecurityGroup
    subnetIds:
      - Ref: PrivateSubnet1
      - Ref: PrivateSubnet2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "execute-api:ManageConnections"
      Resource: "arn:aws:execute-api:us-east-1:*:*/*/*/@connections/*"
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - arn:aws:dynamodb:us-east-1:*:table/ConnectionsTable
        - arn:aws:dynamodb:us-east-1:*:table/EventsHistory
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource:
        - arn:aws:events:us-east-1:442042507897:event-bus/default
    - Effect: Allow
      Action:
        - sns:Publish
        - sns:Subscribe
        - sns:Receive
        - sns:ListTopics
      Resource:
        - '*'

# Incluir solo estos archivos, necesario para reducir el tamano del zip
package:
  patterns:
    - '!**'
    - 'api/rest.py'
    - 'api/websocket.py'
    - 'api/events.py'
    - 'requirements.txt'
    #- 'utils/save_url.py'

functions:
  AllEvents:
    name: AllEventsLambdaFunction 
    handler: api.events.lambda_handler
    package:
      individually: true

  WebsocketConnect:
    name: WebsocketConnect 
    handler: api.websocket.connect
    package:
      individually: true
    events:
      - websocket:
          route: $connect

  WebsocketDisconnect:
    name: WebsocketDisconnect
    handler: api.websocket.disconnect
    package:
      individually: true
    events:
      - websocket:
          route: $disconnect

  WebsocketDefault:
    name: WebsocketDefault
    handler: api.websocket.default
    package:
      individually: true
    events:
      - websocket:
          route: $default

  restApi:
    handler: api.rest.handler
    #package:
    #  individually: true
    #  patterns:
    #      - '!**'
    #      - 'api/rest.py'
    #      - 'requirements.txt'
    events:
      - http:
          path: /v1/events/history
          method: get
          cors: true
      - http:
          path: /v1/operations/types
          method: get
          cors: true
      - http:
          path: /docs
          method: get
          cors: true
      - http:
          path: /openapi.json
          method: get
          cors: true
      - http:
          path: /v1/health
          method: get
          cors: true

  # saveWebsocketUrl:
  #   handler: utils.save_url.lambda_handler
  #   package:
  #     individually: true
  #   timeout: 60

  ArtistProfileCreation:
    name: ArtistProfileCreationLambdaFunction
    handler: api.events.artist_profile_handler
    events:
      - eventBridge:
          eventBus: default
          pattern:
            source:
              - artist-module
            detail-type:
              - artist.profile.created

resources:
  Resources:
    MyVPC:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: 10.0.0.0/16
        EnableDnsSupport: true
        EnableDnsHostnames: true

    InternetGateway:
      Type: AWS::EC2::InternetGateway

    AttachGateway:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        VpcId:
          Ref: MyVPC
        InternetGatewayId:
          Ref: InternetGateway

    PublicSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: MyVPC
        CidrBlock: 10.0.1.0/24
        MapPublicIpOnLaunch: true
        AvailabilityZone: us-east-1a

    PublicSubnet2:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: MyVPC
        CidrBlock: 10.0.2.0/24
        MapPublicIpOnLaunch: true
        AvailabilityZone: us-east-1b

    PrivateSubnet1:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: MyVPC
        CidrBlock: 10.0.3.0/24
        MapPublicIpOnLaunch: false
        AvailabilityZone: us-east-1a

    PrivateSubnet2:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: MyVPC
        CidrBlock: 10.0.4.0/24
        MapPublicIpOnLaunch: false
        AvailabilityZone: us-east-1b

    NatGatewayEIP:
      Type: AWS::EC2::EIP
      DependsOn: AttachGateway
      Properties:
        Domain: vpc

    NatGateway:
      Type: AWS::EC2::NatGateway
      Properties:
        AllocationId:
          Fn::GetAtt:
            - NatGatewayEIP
            - AllocationId
        SubnetId:
          Ref: PublicSubnet1

    PrivateRouteTable1:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: MyVPC

    PrivateRouteTable2:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: MyVPC

    PrivateRoute1:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: PrivateRouteTable1
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: NatGateway

    PrivateRoute2:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: PrivateRouteTable2
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: NatGateway

    SubnetRouteTableAssociationPrivate1:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId:
          Ref: PrivateSubnet1
        RouteTableId:
          Ref: PrivateRouteTable1

    SubnetRouteTableAssociationPrivate2:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId:
          Ref: PrivateSubnet2
        RouteTableId:
          Ref: PrivateRouteTable2

    PublicRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId:
          Ref: MyVPC

    PublicRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId:
          Ref: PublicRouteTable
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId:
          Ref: InternetGateway

    SubnetRouteTableAssociationPublic1:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId:
          Ref: PublicSubnet1
        RouteTableId:
          Ref: PublicRouteTable

    SubnetRouteTableAssociationPublic2:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
        SubnetId:
          Ref: PublicSubnet2
        RouteTableId:
          Ref: PublicRouteTable

    PublicSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow all inbound traffic
        VpcId:
          Ref: MyVPC
        SecurityGroupIngress:
          - IpProtocol: -1
            CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
          - IpProtocol: -1
            CidrIp: 0.0.0.0/0

    AllEventsEventBridgeRule:
      Type: AWS::Events::Rule
      Properties:
        Name: AllEventsEventRule 
        EventBusName: default
        EventPattern:
          source: 
            - "*"
            - "artist-module"
            - "tickets-module"
            - "blockchain-module"
            - "wallet-module"
            - "analytics-module"
            - "ldap-module"
        Targets:
          - Arn:
              Fn::GetAtt: [AllEventsLambdaFunction, Arn]
            Id: AllEventsEventTarget 

    AllEventsLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: 
          Ref: AllEventsLambdaFunction
        Action: lambda:InvokeFunction
        Principal: events.amazonaws.com
        SourceArn: 
          Fn::GetAtt: 
            - AllEventsEventBridgeRule
            - Arn
    
    # Permite a otras cuentas de AWS (sandboxes) enviar eventos a este EDA
    EventBusPolicy:
      Type: AWS::Events::EventBusPolicy
      Properties:
        StatementId: "AllowEventsFromOtherSandboxes1"
        EventBusName: "default"
        Action: "events:PutEvents"
        Principal: "747661705570"

    EventBusPolicy2:
      Type: AWS::Events::EventBusPolicy
      Properties:
        StatementId: "AllowEventsFromOtherSandboxes2"
        EventBusName: "default"
        Action: "events:PutEvents"
        Principal: "637423304975"

    EventBusPolicy3:
      Type: AWS::Events::EventBusPolicy
      Properties:
        StatementId: "AllowEventsFromOtherSandboxes3"
        EventBusName: "default"
        Action: "events:PutEvents"
        Principal: "842961581719"

    EventBusPolicy4:
      Type: AWS::Events::EventBusPolicy
      Properties:
        StatementId: "AllowEventsFromOtherSandboxes4"
        EventBusName: "default"
        Action: "events:PutEvents"
        Principal: "314146339911"

    EventBusPolicy5:
      Type: AWS::Events::EventBusPolicy
      Properties:
        StatementId: "AllowEventsFromOtherSandboxes5"
        EventBusName: "default"
        Action: "events:PutEvents"
        Principal: "185610718112"

    EventBusPolicy6:
      Type: AWS::Events::EventBusPolicy
      Properties:
        StatementId: "AllowEventsFromOtherSandboxes6"
        EventBusName: "default"
        Action: "events:PutEvents"
        Principal: "996851032909"

    EventBusPolicy7:
      Type: AWS::Events::EventBusPolicy
      Properties:
        StatementId: "AllowEventsFromOtherSandboxes7"
        EventBusName: "default"
        Action: "events:PutEvents"
        Principal: "201596100553"

    EventBusPolicy8:
      Type: AWS::Events::EventBusPolicy
      Properties:
        StatementId: "AllowEventsFromOtherSandboxes8"
        EventBusName: "default"
        Action: "events:PutEvents"
        Principal: "416160473082"

    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConnectionsTable
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    
    EventsHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EventsHistory
        AttributeDefinitions:
          - AttributeName: eventId
            AttributeType: S
        KeySchema:
          - AttributeName: eventId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    # ApiGatewayBasePathMapping:
    #   Type: AWS::ApiGateway::BasePathMapping
    #   Properties:
    #     DomainName: deliver.ar
    #     RestApiId:
    #       Ref: ApiGatewayRestApi

    ArtistTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: artist-topic

    ArtistProfileCreatedRule:
      Type: AWS::Events::Rule
      Properties:
        Name: ArtistProfileCreatedRule
        EventPattern:
          source:
            - artist-module
          detail-type:
            - artist.profile.created
        Targets:
          - Arn:
              Fn::GetAtt: [ArtistProfileCreationLambdaFunction, Arn]
            Id: TargetFunction

    RecitalTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: recital-topic

plugins:
  - serverless-python-requirements
  - serverless-scriptable-plugin
  - serverless-domain-manager

custom:
  pythonRequirements:
    dockerizePip: non-linux
    useDownloadCache: true
    useStaticCache: true

  customDomain:
    rest:
      domainName: edaapi.deliver.ar
      stage: dev
      basePath: ''
      certificateName: '*.deliver.ar'
      createRoute53Record: false
      endpointType: REGIONAL
      securityPolicy: tls_1_2
      apiType: rest

    websocket:
      domainName: edaws.deliver.ar
      stage: dev
      basePath: ''
      certificateName: '*.deliver.ar'
      createRoute53Record: false
      endpointType: REGIONAL
      securityPolicy: tls_1_2
      apiType: websocket

  #scriptHooks:
    #after:deploy:finalize: 'aws lambda invoke --function-name eventify-eda-be-dev-saveWebsocketUrl --log-type Tail outfile.txt'